//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public string GUID { get; set; }
        public string ParentID { get; set; }
        public Nullable<int> ChildID { get; set; }
        public Nullable<int> ChildIntNumber { get; set; }
        public Nullable<EChildIntEnum> ChildIntEnum { get; set; }
        public Nullable<decimal> ChildMoney { get; set; }
        public Nullable<System.DateTime> ChildDatetime { get; set; }
        public string ChildVarchar { get; set; }
        public string ChildLongVarchar { get; set; }
        public Nullable<bool> ChildBit { get; set; }
        internal Nullable<byte> ChildTinyintBool_ { get; set; }
        public Nullable<EChildTinyintEnum> ChildTinyintEnum { get; set; }
        public string ChildText { get; set; }
        public byte[] ChildBinary { get; set; }
    
        public virtual Parent Parent { get; set; }
    }
}
