//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Children = new HashSet<Child>();
        }
    
        public string GUID { get; set; }
        public Nullable<int> ParentIntNumber { get; set; }
        public Nullable<EParentIntEnum> ParentIntEnum { get; set; }
        public Nullable<decimal> ParentMoney { get; set; }
        public Nullable<System.DateTime> ParentDatetime { get; set; }
        public string ParentVarchar { get; set; }
        public string ParentLongVarchar { get; set; }
        public Nullable<bool> ParentBit { get; set; }
        internal Nullable<sbyte> ParentTinyintBool_ { get; set; }
        public Nullable<EParentTinyintEnum> ParentTinyintEnum { get; set; }
        public string ParentText { get; set; }
        public byte[] ParentBinary { get; set; }
    
        public virtual ICollection<Child> Children { get; set; }
    }
}
